# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080

# 语音识别配置
xfyun:
  app_id: "c0de4f24"
  api_key: "51012a35448538a8396dc564cf050f68"
  api_secret: "NWRhZDBkNzA5ZDQxNGMzYmQ1NWMwMWNh"
  server_url: "wss://iat-api.xfyun.cn/v2/iat"
  max_retries: 3
  reconnect_interval: 1

# Ollama配置
ollama:
  host: "http://localhost:11434"
  model: "qwen:0.5b"

# WebSocket配置
websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  ping_period: "30s"
  pong_wait: "60s"

# MySQL配置
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  database: "ai_dialer"

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
